---
- hosts: 127.0.0.1
  tasks:
  - name: install apt packages
    become: true
    apt:
      name: 
      - lsb-release
      - composer
      - git
      - snapd
      - neovim-qt
      - xclip  
      - htop
  - name: Install snaps with classic consignment
    become: true
    snap:
      name: 
        - phpstorm
        - skype
        - atom
      classic: yes
  - name: Install snaps
    become: true
    snap:
      name:
        - docker
