---
- hosts: 127.0.0.1
  tasks:
  - name: install apt packages
    become: true
    apt:
      name: 
      - lsb-release
      - composer
      - git
      - snapd
      - neovim-qt
  - name: Download vim package manager
    become: true
    get_url:
      url: https://raw.githubusercontent.com/egalpin/apt-vim/master/install.sh
      dest: ~/install.sh
      mode: 0777
  - name: Install the package manager
    command: sh ~/install.sh
  - name: Install PHPStorm
    become: true
    snap:
      name: phpstorm
      classic: yes
